In [14]:
# Q1

import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)
print(type(list_))
print(type(array_list))


<class 'list'>
<class 'numpy.ndarray'>


In [21]:
# Q2

for i in list_:
    print(type(i))
for i in array_list:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [24]:
# Q3

#YES str changed to int in array_list


array_list = np.array(object = list_, dtype = int)
print(array_list)


for i in list_:
    print(type(i))
for i in array_list:
    print(type(i))

[1 2 3 4 5]
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [29]:
# Q4

import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
print(num_array.shape)
print(num_array.size)

(2, 3)
6


In [34]:
# Q5

np1= np.zeros((3,3),int)
print(np1)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [43]:
# Q6

np2=np.eye(5)
print(np2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
